apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitalapi
spec:
  selector:
    matchLabels:
      app: digitalapi
  replicas: 2
  template:
    metadata:
      labels:
        app: digitalapi
    spec:
      containers:
      - name: digitalapi
        image: python:3.7-slim-stretch
        ports:
        - containerPort: 8080
